//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSportsTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchAttribute
    {
        public int MatchID { get; set; }
        public string ValueOf { get; set; }
        public int PlayerID { get; set; }
        public int AttributeID { get; set; }
    
        public virtual AttributesTable AttributesTable { get; set; }
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
