//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSportsTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchMaker
    {
        public System.TimeSpan TimePlayed { get; set; }
        public int TournamentID { get; set; }
        public int Winner { get; set; }
        public int Loser { get; set; }
        public int GameID { get; set; }
    }
}
