//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSportsTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchesView
    {
        public int MatchID { get; set; }
        public string TournamentName { get; set; }
        public string Winner { get; set; }
        public string Loser { get; set; }
        public string GameName { get; set; }
    }
}
