//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSportsTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerWithWin
    {
        public string Handle { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
    }
}
