//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSportsTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentDetailsExtended
    {
        public int TournamentID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Organizer { get; set; }
        public string Location { get; set; }
        public string Game { get; set; }
        public string Participant { get; set; }
    }
}
